### PR TITLE
Use Red Hat provided redis image as default

### PR DESCRIPTION
**Pull request by shubhamagarwal19**
This is in accordance to PR https://github.com/argoproj-labs/argocd-operator/pull/238.

GitOps operator by default should use a Red Hat provided redis image.

### CODE REVIEW

**Review by bigkevmcd — DISMISSED** [review]

**Comment by chetan-rns** [comment]
Should we allow reading this image from an env variable for disconnected environments?
Example: https://github.com/redhat-developer/gitops-operator/blob/d473346f071cc38b54402bf402c863aabd7fcd38/pkg/controller/gitopsservice/kam.go#L29

Unit test for the above example can be found here https://github.com/redhat-developer/gitops-operator/blob/d473346f071cc38b54402bf402c863aabd7fcd38/pkg/controller/gitopsservice/gitopsservice_controller_test.go#L23

**Comment by wtam2018** [comment]
@shubhamagarwal19  thanks for raising the PR.  Setting the redis image should be done by setting the environment variable in CSV. 
```
 name: ARGOCD_REDIS_IMAGE
 value: registry.redhat.io/rhel8/redis-5 
```

**Comment by shubhamagarwal19** [comment]
@wtam2018, thanks for the comment. Updated the CSV with `ARGOCD_REDIS_IMAGE` ENV!

**Pull request merged**
