### PR TITLE
[draft] Add scripts to run kuttl tests against olm packaged operator

### PR DESCRIPTION
**Pull request by praveen4g0**
**What type of PR is this?**

> /kind enhancement

**What does this PR do / why we need it**:
* It ensures to run kuttl tests against installed olm packaged operator, 
* ensures tests run independently doesn't have worry about adding hacks (like adding RBACS., in case ginkgo )

**Which issue(s) this PR fixes**:

This PR build the operator (operator image, bundle catalog source,  index image). t/his PR push all images to an image registry as parameter (default is the internal registry)

Fixes [#2224](https://issues.redhat.com/browse/GITOPS-2224)

**Test acceptance criteria**:
* [x] E2E Test

**How to test changes / Special notes to the reviewer**:
```
* It now adds new make target to run kuttl tests, As part of spike I have created couple of kuttl tests.
* Next step is to migrate all ginkgo tests to kuttl, will handle it in another pr

**steps to run kuttl tests**

export IMAGE="quay.io/<username>/gitops-backend-operator"
export VERSION="v0.0.1"
# Now we support few ENV values to help run them locally
# 1. E2E_SKIP_OPERATOR_INSTALLATION if you set this `true`, It doesn't install operator
# 2. E2E_SKIP_BUILD_TOOL_INSTALLATION if you set this flag to `true`, It won't install operator-sdk and opm tools required to build olm bundle at runtime.

# Run below script to tests the changes  
./scripts/openshiftci-olm-kuttl-tests.sh
```

### CODE REVIEW

**Comment by wtam2018** [comment]
How come there are no ci tests running? @praveen4g0

**Comment by praveen4g0** [comment]
> How come there are no ci tests running? @praveen4g0

I am not sure :thinking:

**Comment by praveen4g0** [comment]
we are tracking all this changes in [PR-367](https://github.com/redhat-developer/gitops-operator/pull/367l)

**Pull request closed without merging**
