### PR TITLE
fix: minor fixes in non-olm install script and doc

### PR DESCRIPTION
**Pull request by saumeya**
**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

> /kind bug

**What does this PR do / why we need it**:

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes a typo in script which is needed to install nightly image.

**Test acceptance criteria**:

* [ ] Unit Test
* [ ] E2E Test

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Review by anandf — APPROVED** [review]

**Review by iam-veeramalla — APPROVED** [review]
/lgtm
/approve

**Comment by varshab1210** [comment]
This PR can be merged considering **1-050_validate_sso_config ** as a known issue (https://issues.redhat.com/browse/GITOPS-2929)

cc: @anandf @iam-veeramalla

**Pull request merged**
