### PR TITLE
Update Argo CD operator version

### PR DESCRIPTION
**Pull request by chetan-rns**
PR to support cluster config management has been merged to upstream ArgoCD operator. This commit will update the Argo CD version to include the latest changes for TP

### CODE REVIEW

**Review by bigkevmcd — APPROVED** [review]

**Comment by sbose78** [comment]
Need to add the new CRD.

**Comment by sbose78** [comment]
already done in https://github.com/redhat-developer/gitops-operator/pull/33 .
Could you please raise a PR to add the updated CRDs ?

**Pull request closed without merging**
