### PR TITLE
test: Add e2e test for redis ha

### PR DESCRIPTION
**Pull request by svghadi**
**What type of PR is this?**
/kind test

**What does this PR do / why we need it**:
Adds e2e test for [GITOPS-2404](https://issues.redhat.com/browse/GITOPS-2404)

### CODE REVIEW

**Comment by svghadi** [comment]
Closing this in favour of #534. Same set of changes are included there.

**Comment by mehabhalodiya** [comment]
Sorry @svghadi I didn't notice this PR.

**Comment by svghadi** [comment]
No worries. We can get these changes in with your PR.

**Pull request closed without merging**
