### PR TITLE
chore: Bump go to 1.22

### PR DESCRIPTION
**Pull request by svghadi**
**What does this PR do / why we need it**:
Bump golang to 1.22

### CODE REVIEW

**Comment by svghadi** [comment]
@varshab1210 - Are these known failures?
```
        --- FAIL: kuttl/harness/1-067_validate_redis_secure_comm_no_autotls_ha (162.10s)
        --- FAIL: kuttl/harness/1-066_validate_redis_secure_comm_no_autotls_no_ha (37.84s)
```

**Comment by varshab1210** [comment]
> @varshab1210 - Are these known failures?
> 
> ```
>         --- FAIL: kuttl/harness/1-067_validate_redis_secure_comm_no_autotls_ha (162.10s)
>         --- FAIL: kuttl/harness/1-066_validate_redis_secure_comm_no_autotls_no_ha (37.84s)
> ```

> req: Multiple digest or unknown options: -sha256 and -sha256

Could you please remove one of the sha256 options? That should fix the failure

**Comment by varshab1210** [comment]
LGTM, thanks

**Pull request merged**
