### PR TITLE
fix: argocd-tls-certs-cm gets overwritten by the operator

### LINKED ISSUE #271: argocd-tls-certs-cm is overwritten by the operator (v1.4.0)
**Describe the bug**
Prior to v1.4.0 of OpenShift GitOps, certificates for TLS validation could be managed via the ArgoCD GUI or by controlling the argocd-tls-certs-cm ConfigMap directly. The value of argocd-tls-certs-cm was set initially when ArgoCD was deployed but not altered thereafter.

After upgrading to v1.4.0, this ConfigMap is reset to the value of tls.intitialCerts in the ArgoCD CR after any change. This renders the certificate management via the GUI or previous direct ConfigMap control useless and deletes any certificates that were added to the ConfigMap prior to the upgrade.

Workaround:  Add the needed cert to ArgoCD CR spec  tls.initialCerts.  See https://argocd-operator.readthedocs.io/en/latest/reference/argocd/#tls-options

**Additional context**

### PR DESCRIPTION
**Pull request by iam-veeramalla**
Signed-off-by: iam-veeramalla <abhishek.veeramalla@gmail.com>

**What type of PR is this?**
> /kind enhancement

**What does this PR do / why we need it**:
fixes #271 

**Which issue(s) this PR fixes**:
Fixes #271 

**How to test changes / Special notes to the reviewer**:
-------------------------

1. Run the operator locally using `make install run`
2. Create an Argo CD Instance or use the default Argo CD instance.
3. Add a cert to argocd-tls-certs-cm configmap.
```
..........
data:
  test.example.com: '-----BEGIN CERTIFICATE-----  -----END CERTIFICATE-----'
```
4. operator SHOULD NOT remove the configmap changes added manually in step 3.

### CODE REVIEW

**Comment by iam-veeramalla** [comment]
@wtam2018 please approve

**Comment by wtam2018** [comment]
The "How to test" seems to be the steps to validate the helm CVE issue not the "argocd-tls-certs-cm is overwritten by the operator" issue.

And the ci didn't run.

**Comment by iam-veeramalla** [comment]
> /

@wtam2018 updates the steps to test. Somehow the CI is not running.

**Review by wtam2018 — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
