### PR TITLE
chore: Fix typos in "argocd" mentions in usage guide

### PR DESCRIPTION
**Pull request by jaideepr97**
**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

> /kind bug
> /kind cleanup
> /kind failing-test
> /kind enhancement
 /kind documentation
> /kind code-refactoring

**What does this PR do / why we need it**:
fixes typos in technical text containing the term `argocd`

**Have you updated the necessary documentation?**

* [x] Documentation update is required by this PR.
* [x] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

**Test acceptance criteria**:

* [ ] Unit Test
* [ ] E2E Test

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Review by jannfis — COMMENTED** [review]
LGTM

**Comment by jaideepr97** [comment]
@jannfis could you approve this? Thanks

**Pull request merged**
