### PR TITLE
env var for cluster config in deployment manifest

### PR DESCRIPTION
**Pull request by sbose78**
Use https://github.com/argoproj-labs/argocd-operator/blob/8aa14c03df16b634d6f01ac309f727f8645a6c4e/pkg/reconciler/openshift/openshift.go#L21

### CODE REVIEW

**Comment by chetan-rns** [comment]
@sbose78 Since we have a single bundle, is the default value `openshift-gitops` valid for a 4.6 cluster?

**Comment by sbose78** [comment]
If you are handling 4.6 separately, I would say No :) this is valid for 4.7 only.

**Comment by sbose78** [comment]
I'll rescind what I said, and keep things simple. Let this be valid for all versions of openshift. That means, 4.6 will get a "app delivery" ArgoCD, that's fine in my opinion.

**Review by bigkevmcd — APPROVED** [review]

**Pull request merged**
