### PR TITLE
test: use `t.Setenv` to set env vars

### PR DESCRIPTION
**Pull request by Juneezee**
**What type of PR is this?**
/kind cleanup

**What does this PR do / why we need it**:

Starting from Go 1.17, we can use `t.Setenv` to set environment variable in test. The environment variable is automatically restored to its original value when the test and all its subtests complete. This ensures that each test does not start with leftover environment variables from previous completed tests.

Reference: https://pkg.go.dev/testing#T.Setenv

```go
func TestFoo(t *testing.T) {
	// before
	os.Setenv(key, "new value")
	defer os.Unsetenv(key)
	
	// after
	t.Setenv(key, "new value")
}
```

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

**Test acceptance criteria**:

* [x] Unit Test
* [ ] E2E Test

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by wtam2018** [comment]
thanks @Juneezee !

**Comment by Juneezee** [comment]
Hi @iam-veeramalla. whenever you have some free time, I would greatly appreciate it if you could take a look at this PR. Thank you in advance for your time and consideration.

**Pull request merged**
