### PR TITLE
Disable flaky e2e tests

### PR DESCRIPTION
**Pull request by svghadi**
**What type of PR is this?**
/kind failing-test

**What does this PR do / why we need it**:
This PR disables flaky e2e tests to unblock tide PR merges by moving them to `test/openshift/e2e/ignore-tests/` folder. These test failures are addressed in separate PRs and will be enabled again in those PRs. 

|Test|Issue|PR to fix test|
|:-:|:-:|:-:|
|1-004_validate_argocd_installation|
|1-005_validate_metrics|
|1-006_validate_machine_config|[GITOPS-2844](https://issues.redhat.com/browse/GITOPS-2844)||
|1-010_validate-ootb-manage-other-namespace|[GITOPS-2997](https://issues.redhat.com/browse/GITOPS-2997)|
|1-018_validate_disable_default_instance|[GITOPS-2829](https://issues.redhat.com/browse/GITOPS-2829)|#540|
|1-027_validate_operand_from_git|[GITOPS-2838](https://issues.redhat.com/browse/GITOPS-2838)
|1-031_validate_toolchain|
|1-035_validate_argocd_secret_repopulate|[GITOPS-2998](https://issues.redhat.com/browse/GITOPS-2998)|#543|
|1-042_validate_status_host|[GITOPS-2985](https://issues.redhat.com/browse/GITOPS-2985)|#530|
|1-064_validate_tcp_reset_error|[GITOPS-3078](https://issues.redhat.com/browse/GITOPS-3078)|#561|
|1-083_validate_apps_in_any_namespace|[GITOPS-2874](https://issues.redhat.com/browse/GITOPS-2874)|https://github.com/argoproj-labs/argocd-operator/pull/939|
|||
|parallel/1-009_validate-manage-other-namespace|[GITOPS-2826](https://issues.redhat.com/browse/GITOPS-2826)|
|parallel/1-055_validate_notification_controller|[GITOPS-2857](https://issues.redhat.com/browse/GITOPS-2857)|
|parallel/1-057_validate_notifications|[GITOPS-3076](https://issues.redhat.com/browse/GITOPS-3076)||
|parallel/1-068_validate_redis_secure_comm_autotls_no_ha|[GITOPS-3077](https://issues.redhat.com/browse/GITOPS-3077)||

### CODE REVIEW

**Comment by varshab1210** [comment]
Hi @svghadi, I have raised PRs for fixing **1-042_validate_status_host** and **1-035_validate_argocd_secret_repopulate** could you please take a look? Hopefully it'll fix them.
 
https://github.com/redhat-developer/gitops-operator/pull/530 
https://github.com/redhat-developer/gitops-operator/pull/545

**Comment by ciiay** [comment]
@svghadi I also have a PR for 1-083_validate_apps_in_any_namespace, could you please take a look too?
https://github.com/argoproj-labs/argocd-operator/pull/939

**Comment by iam-veeramalla** [comment]
great work @svghadi

**Pull request merged**
