### PR TITLE
update argocd-operator for v1.12

### PR DESCRIPTION
**Pull request by anandrkskd**
**What type of PR is this?**

/kind cleanup

**What does this PR do / why we need it**:
This PR updates argocd-operator version

### CODE REVIEW

**Review by ishitasequeira — APPROVED** [review]
/lgtm
/approve

**Review by svghadi — APPROVED** [review]
/lgtm

**Comment by varshab1210** [comment]
LGTM

**Review by anandf — APPROVED** [review]
LGTM

**Pull request merged**
