### PR TITLE
Don't poll if the required resources are available

### PR DESCRIPTION
**Pull request by chetan-rns**
**What type of PR is this?**

> /kind bug

**What does this PR do / why we need it**:

The `wait.Poll()` will run until the function returns true, error or a timeout occurs.  This PR updates the function to return true if the resources are available in the cluster which otherwise would never stop the poll resulting in a timeout. 

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

**Test acceptance criteria**:

* [ ] Unit Test
* [ ] E2E Test

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by jgwest** [comment]
@chetan-rns  looks like this was already merged in by your other PR :smile:

**Comment by chetan-rns** [comment]
Closing this PR since the change already landed with #153

**Pull request closed without merging**
