### PR TITLE
chore: pickup multiple sso validation

### PR DESCRIPTION
**Pull request by jaideepr97**
**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

> /kind bug
> /kind cleanup
> /kind failing-test
/kind enhancement
> /kind documentation
> /kind code-refactoring

**What does this PR do / why we need it**:
Picks up multiple sso configuration validation from argocd-operator 

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

N/A

**Test acceptance criteria**:

* [ ] Unit Test
* [ ] E2E Test

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by wtam2018** [comment]
There is CRD change.

**Comment by iam-veeramalla** [comment]
Tests Failure:
`panic: test timed out after 10m0s`

We should merge https://github.com/redhat-developer/gitops-operator/pull/227 first to avoid such errors

**Comment by iam-veeramalla** [comment]
@jannfis Can you please approve this ? we lost @wtam2018 approval due to a test update.

**Pull request merged**
