### PR TITLE
chore: update argocd operator

### PR DESCRIPTION
**Pull request by chetan-rns**
**What does this PR do / why we need it**:
Updates the argocd operator to the latest version that includes the following fixes:

https://github.com/argoproj-labs/argocd-operator/pull/488
https://github.com/argoproj-labs/argocd-operator/pull/516
https://github.com/argoproj-labs/argocd-operator/pull/518
https://github.com/argoproj-labs/argocd-operator/pull/519
https://github.com/argoproj-labs/argocd-operator/pull/511
https://github.com/argoproj-labs/argocd-operator/pull/507
https://github.com/argoproj-labs/argocd-operator/issues/498
https://github.com/argoproj-labs/argocd-operator/pull/499
https://github.com/argoproj-labs/argocd-operator/pull/505

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

**Test acceptance criteria**:

* [ ] Unit Test
* [ ] E2E Test

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by chetan-rns** [comment]
@iam-veeramalla  @jaideepr97 The unit tests were failing because of changes to the latest SSO spec. I've included the fix. Please take a look!

**Comment by iam-veeramalla** [comment]
> @iam-veeramalla  @jaideepr97 The unit tests were failing because of changes to the latest SSO spec. I've included the fix. Please take a look!

Thanks for raising this PR. I will take a look

**Comment by jaideepr97** [comment]
@chetan-rns 
Thanks for raising this PR, I had raised a draft one earlier that covered some of these changes, but this is more up to date since the sso changes have now gone into master
I think there will be some manifest changes in argocd-operator that should probably be included in this PR 
https://github.com/redhat-developer/gitops-operator/pull/247 for reference

**Comment by chetan-rns** [comment]
@jaideepr97 Sorry! I'm closing this PR since it's a duplicate of #247

**Pull request closed without merging**
