### PR TITLE
pick-up 1.3.2 bug fixes 

### PR DESCRIPTION
**Pull request by jaideepr97**
**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

> /kind bug
> /kind cleanup
> /kind failing-test
 /kind enhancement
> /kind documentation
> /kind code-refactoring

**What does this PR do / why we need it**:
Picks up bug fixes for v1.3.2 from the rhos-v1.3 branch of argocd-operator 

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

**Test acceptance criteria**:

* [ ] Unit Test
* [ ] E2E Test

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by iam-veeramalla** [comment]
Hi @jaideepr97 , Did you check if any of these changes have updates/modifications to CSV, CRD or other manifest files ?

**Comment by jaideepr97** [comment]
@iam-veeramalla 
Yes, neither of the 2 upstream commits included in this change involve any manifest changes

**Comment by iam-veeramalla** [comment]
awesome, lets keep this PR open and update it when all the changes for 1.3 are done ?

**Comment by jaideepr97** [comment]
@iam-veeramalla Sure
But I think for 1.3.2, from an operator code perspective I don't think there are any more pending changes  
All other changes are in cpaas

**Pull request merged**
