### PR TITLE
Rebase master branch with v1.8 changes

### PR DESCRIPTION
**Pull request by iam-veeramalla**
**What type of PR is this?**
> /kind code-refactoring

**What does this PR do / why we need it**:
Rebase GitOps Operator Master branch with v1.8 branch changes. While it looks like there are many changes missing in the master branch, most of the them are the commits where I tried the render_templates implementation.

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Review by wtam2018 — COMMENTED** [review]
@iam-veeramalla Please make sure the CSV and other manifests in bundle are generated (and be reproduced) by running `make bundle`.

**Comment by iam-veeramalla** [comment]
Will create a new PR to make the review simpler

**Pull request closed without merging**
