### PR TITLE
feat: Add e2e test to verify server autoscale behavior 

### PR DESCRIPTION
**Pull request by jaideepr97**
**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

> /kind bug
> /kind cleanup
> /kind failing-test
> /kind enhancement
> /kind documentation
> /kind code-refactoring

**What does this PR do / why we need it**:
adds an e2e test to verify that operator behaves as expected when server autoscale is enabled

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

**Test acceptance criteria**:

* [ ] Unit Test
* [ ] E2E Test

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by bluengo** [comment]
/lgtm

Kuttl test is working fine with build **1.8.3-1** (checked in OCP 4.11) 👍
```bash
--- PASS: kuttl (107.11s)
    --- PASS: kuttl/harness (0.00s)
        --- PASS: kuttl/harness/1-099_validate_server_autoscale (96.11s)
PASS
```

**Comment by varshab1210** [comment]
/pj-rehearse pull-ci-redhat-developer-kam-master-v4.11-integration-e2e

**Comment by varshab1210** [comment]
Closing this, please reopen if required

**Pull request closed without merging**
