### PR TITLE
Import openshift package from argocd-operator to enable hooks

### PR DESCRIPTION
**Pull request by chetan-rns**
**What type of PR is this?**

> /kind bug

**What does this PR do / why we need it**:

Fixes: #199 

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

**Test acceptance criteria**:

* [ ] Unit Test
* [ ] E2E Test

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by iam-veeramalla** [comment]
@chetan-rns did you run some tests ? 

With this change, `argocd-application-controller` created by the`gitops-operator` in the default namespace should be able to manage cluster config resources like machinesets, images e.t.c.,. The easiest way to verify the change should be by looking at the role/clusterrole.

**Comment by chetan-rns** [comment]
@iam-veeramalla Yes. RBAC for managing cluster config is created

**Comment by iam-veeramalla** [comment]
@chetan-rns Thanks !!

**Pull request merged**
