### PR TITLE
chore: upgrade operator-sdk to 1.35

### PR DESCRIPTION
**Pull request by anandrkskd**
**What type of PR is this?**
/kind cleanup

**What does this PR do / why we need it**:
This PR updates operator-sdk version from 1.32.0 to 1.35.0. 

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

**Test acceptance criteria**:

* [ ] Unit Test
* [ ] E2E Test

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by saumeya** [comment]
We are not using `internal` in this either?

**Review by saumeya — COMMENTED** [review]
Left one comment, else looks good to me. Thanks Anand!

**Comment by anandrkskd** [comment]
> We are not using `internal` in gitops-operator either?

No @saumeya, as per last discussion with you and @svghadi, AFAIR we decided not to make changes to the `controllers`, as it might affect if other projects are using this repo as dependency.

@svghadi, @iam-veeramalla WDYT?

**Comment by svghadi** [comment]
Yes, let's avoid moving to the `internal/` directory structure for now. We can re-evaluate this decision during the refactoring efforts if needed.

**Review by svghadi — COMMENTED** [review]
/lgtm

**Pull request merged**
