### PR TITLE
Upgrade to go 1.16

### PR DESCRIPTION
**Pull request by davidkarlsen**
Upgrade to go 1.16.x

Signed-off-by: David J. M. Karlsen <david@davidkarlsen.com>

**What type of PR is this?**
/kind cleanup
/kind enhancement

**What does this PR do / why we need it**:
Upgrades to to recent version

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?
#69

**How to test changes / Special notes to the reviewer**:
N/A

### CODE REVIEW

**Comment by wtam2018** [comment]
Last I looked (last week), the openshift 1.16 golang container was not found.

**Comment by davidkarlsen** [comment]
> Last I looked (last week), the openshift 1.16 golang container was not found.

Well, it's there now at least: 
```
docker pull openshift/origin-release:golang-1.16
golang-1.16: Pulling from openshift/origin-release
2d473b07cdd5: Pull complete 
92aabcd08403: Extracting [===============>                                   ]  110.3MB/346.2MB
```

**Comment by wtam2018** [comment]
@davidkarlsen thanks
/ok-to-test

**Comment by davidkarlsen** [comment]
> @davidkarlsen thanks
> /ok-to-test

thanks, could you also comment on the other issues I've reported? WDYT?

**Comment by wtam2018** [comment]
/lgtm
/approve
Thanks @davidkarlsen !

**Comment by amitkrout** [comment]
@davidkarlsen Please rebase the pr

**Comment by davidkarlsen** [comment]
@amitkrout it passes now

**Pull request merged**
