### PR TITLE
GITOPS-2690 adding all the example used in testing from different sources

### PR DESCRIPTION
**Pull request by anandrkskd**
**What type of PR is this?**

/kind enhancement

**What does this PR do / why we need it**:
- adds examples for tests from https://github.com/argoproj/argocd-example-apps, https://github.com/bluengo/argocd-apps-examples, https://github.com/jaideepr97/gitops-examples, https://github.com/jannfis/operator-e2e-git used for testing of gitops-operator
-  ~updates tests to use these example instead of examples present in different repositories.~ (I will cover this on a seperate PR)

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes GITOPS-2690

**Test acceptance criteria**:

* [ ] Unit Test
* [ ] E2E Test

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by anandrkskd** [comment]
Some tests are failing with 
```shell
        +  - lastTransitionTime: "2023-07-18T07:13:53Z"
        +    message: 'rpc error: code = Unknown desc = Manifest generation error (cached):
        +      test/examples/kustomize-guestbook: app path does not exist'
```
As the tests are pointed to HEAD for example path, 
We can merge this PR without modification to the tests and then make changes to test on a separate PR to test if the tests are working as expected or not. 
@varshab1210 @trdoyle81 @iam-veeramalla, WDYT?

**Comment by mehabhalodiya** [comment]
It's just a rebase, so adding the label again.

/lgtm

**Pull request merged**
