### PR TITLE
update argocd-operator version

### PR DESCRIPTION
**Pull request by anandrkskd**
**What type of PR is this?**

 /kind cleanup

**What does this PR do / why we need it**:
This PR is updating argocd-operator version.

### CODE REVIEW

**Review by anandf — APPROVED** [review]
LGTM

**Comment by svghadi** [comment]
This test needs update
https://github.com/redhat-developer/gitops-operator/blob/50d51d13e09337bfcd0c6425374b3cb2d793e248/test/openshift/e2e/parallel/1-031_validate_toolchain/01-check.yaml#L11

**Pull request merged**
