### PR TITLE
fix: add security context to kam and cluster pods

### PR DESCRIPTION
**Pull request by jaideepr97**
**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

 /kind bug
> /kind cleanup
> /kind failing-test
> /kind enhancement
> /kind documentation
> /kind code-refactoring

**What does this PR do / why we need it**:
Adds security contexts to kam and backend pods so that they are in compliance with OCP pod security requirements

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

**Test acceptance criteria**:

* [ ] Unit Test
* [ ] E2E Test

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by varshab1210** [comment]
**[1-001_validate_kam_service](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-developer_gitops-operator/451/pull-ci-redhat-developer-gitops-operator-master-v4.10-kuttl-sequential/1632024085934379008#1:build-log.txt%3A694)** and **[1-002_validate_backend_service](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-developer_gitops-operator/451/pull-ci-redhat-developer-gitops-operator-master-v4.10-kuttl-sequential/1632024085934379008#1:build-log.txt%3A2075)** are failing on all three platforms which is not expected.

I checked with 1.8.0 RC, the tests are passing.

cc: @iam-veeramalla @wtam2018

**Comment by wtam2018** [comment]
Why 1-001_validate_kam_service and 1-002_validate_backend_service are failing on all three platforms which is not expected? @varshab1210

**Comment by varshab1210** [comment]
> Why 1-001_validate_kam_service and 1-002_validate_backend_service are failing on all three platforms which is not expected? @varshab1210

I don't know, this is what I see from the logs
message: Deployment does not have minimum availability.`
message: 'pods "cluster-749b8b8c6d-tjq7h" is forbidden: unable to validate against
        +      any security context constraint: [pod.metadata.annotations.container.seccomp.security.alpha.kubernetes.io/cluster:
        +      Forbidden: seccomp may not be set provider "anyuid": Forbidden: not usable by
        +      user or serviceaccount provider "nonroot": Forbidden: not usable by user or
        +      serviceaccount provider "hostmount-anyuid": Forbidden: not usable by user or
        +      serviceaccount provider "machine-api-termination-handler": Forbidden: not usable
        +      by user or serviceaccount provider "hostnetwork": Forbidden: not usable by user
        +      or serviceaccount provider "hostaccess": Forbidden: not usable by user or serviceaccount
        +      provider "node-exporter": Forbidden: not usable by user or serviceaccount provider
        +      "privileged": Forbidden: not usable by user or serviceaccount]'`

**Comment by drpaneas** [comment]
The code looks good to me /lgtm
Thank you @varshab1210

**Pull request merged**
