### PR TITLE
updated Argo CD 2.7.6 CRDs and argocd-operator

### PR DESCRIPTION
**Pull request by reginapizza**
**What type of PR is this?**
 /kind enhancement

**What does this PR do / why we need it**:
Argocd-operator was [updated with the latest CRDs](https://github.com/argoproj-labs/argocd-operator/pull/944) from [Argo CD 2.7.6](https://github.com/argoproj/argo-cd/tree/v2.7.6/manifests/crds), this PR pulls in those changes and updates CRDs to match. 

**Have you updated the necessary documentation?**
NA

I know that the changes to CRDs include adding in typos but that's what's in upstream... :upside_down_face:

### CODE REVIEW

**Comment by jaideepr97** [comment]
@reginapizza the version still says 1.8.0 in the CSV 
we should probably have updated that earlier

**Comment by iam-veeramalla** [comment]
@jaideepr97 the version update in the CSV is handled by render templates :)

**Comment by reginapizza** [comment]
Is it ok to merge this PR? It keeps failing because of what I believe are just flakey tests

**Pull request merged**
