### PR TITLE
test: Avoid displaying argocd-secret in the test log

### PR DESCRIPTION
**Pull request by varshab1210**
**What type of PR is this?**

 /kind cleanup

**What does this PR do / why we need it**:

Removes the line exposing argocd-secret which was originally added for debugging 

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

**Test acceptance criteria**:

* [ ] Unit Test
* [ ] E2E Test

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by varshab1210** [comment]
CI issues
/retest

**Comment by varshab1210** [comment]
/test v4.14-kuttl-parallel

CI issues

**Review by anandrkskd — APPROVED** [review]
/lgtm

**Pull request merged**
