### PR TITLE
Fix haproxy crash part 2 (master)

### PR DESCRIPTION
**Pull request by jopit**
Signed-off-by: John Pitman <jpitman@redhat.com>

**What type of PR is this?**
/kind bug

**What does this PR do / why we need it**:

Fixes haproxy not starting up for older versions of OpenShift

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

**Test acceptance criteria**:

* [ ] Unit Test
* [ ] E2E Test

**How to test changes / Special notes to the reviewer**:

Run against OpenShift 4.10 or older. Run the operator with the OpenShift Redis related images.
```bash
ARGOCD_REDIS_IMAGE=registry.redhat.io/rhel8/redis-6@sha256:53598a6effeb90e4f1b005b2521beffd2fa2b0c52d0e7f2347ee2abd2577cab3 \
ARGOCD_REDIS_HA_IMAGE=registry.redhat.io/rhel8/redis-6@sha256:53598a6effeb90e4f1b005b2521beffd2fa2b0c52d0e7f2347ee2abd2577cab3 \
ARGOCD_REDIS_HA_PROXY_IMAGE=registry.redhat.io/openshift4/ose-haproxy-router@sha256:edf7ce748b703e195220b7bd7b42fa2caa4cdfd96840445e096036a0d85f1ff2 \
REDIS_CONFIG_PATH="build/redis" \
make install run
```
Install an Argo CD instance
```yaml
apiVersion: argoproj.io/v1alpha1
kind: ArgoCD
metadata:
  name: argocd
spec:
  ha:
    enabled: true
```
Check that the `argocd-redis-ha-haproxy` pod starts successfully.

### CODE REVIEW

**Comment by saumeya** [comment]
Tested and works on 4.9

**Comment by jopit** [comment]
Hi @iam-veeramalla. could you remove the hold and re-approve this please?

**Comment by iam-veeramalla** [comment]
unhold

**Pull request merged**
