### PR TITLE
chore: Upgrade argocd

### PR DESCRIPTION
**Pull request by svghadi**
**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

> /kind bug
> /kind cleanup
> /kind failing-test
> /kind enhancement
> /kind documentation
> /kind code-refactoring

**What does this PR do / why we need it**:

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

**Test acceptance criteria**:

* [ ] Unit Test
* [ ] E2E Test

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by svghadi** [comment]
Test failure
```
    logger.go:42: 14:22:13 | 1-031_validate_toolchain/1-check | Kustomize version mismatch. Should be v5.4.2, is v5.4.3
    logger.go:42: 14:22:13 | 1-031_validate_toolchain/1-check | Helm version mismatch. Should be v3.15.2, is v3.15.4
    logger.go:42: 14:22:13 | 1-031_validate_toolchain/1-check | 
```

**Comment by Mangaal** [comment]
lgtm

**Review by Mangaal — APPROVED** [review]
lgtm

**Review by chetan-rns — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
