### PR TITLE
chore: Update argocd-operator to fix sso test failure

### PR DESCRIPTION
**Pull request by svghadi**
**What type of PR is this?**
/kind failing-test

**What does this PR do / why we need it**:
`1-050_validate_sso_config` test is flaky due to a bug in argocd-operator which has been fixed with https://github.com/argoproj-labs/argocd-operator/pull/922. This PR updates argocd-operator version to include that fix. 

**Which issue(s) this PR fixes**:

Fixes [GITOPS-2929](https://issues.redhat.com/browse/GITOPS-2929)

**How to test changes / Special notes to the reviewer**:
`1-050_validate_sso_config` test should pass consistently in openshift-ci

### CODE REVIEW

**Review by jaideepr97 — APPROVED** [review]

**Comment by iam-veeramalla** [comment]
--- FAIL: kuttl/harness/1-042_validate_status_host (59.71s)
 
 the above is a flaky test that is failing.

**Pull request merged**
