### PR TITLE
feat: create RHSSO using sso template instance (#GITOPS-841)

### PR DESCRIPTION
**Pull request by iam-veeramalla**
Signed-off-by: iam-veeramalla <abhishek.veeramalla@gmail.com>

**What type of PR is this?**
> /kind enhancement

**What does this PR do / why we need it**:
GITOPS-841

**Have you updated the necessary documentation?**
Document will be updated together with the follow up stories. A detailed doc for this is already available [here](https://deploy-preview-30615--osdocs.netlify.app/openshift-enterprise/latest/cicd/gitops/configuring-sso-for-argo-cd-on-openshift.html#registering-an-additional-oauth-client_configuring-sso-for-argo-cd-on-openshift)

**Which issue(s) this PR fixes**:
GITOPS-841

Fixes #?
GITOPS-841

**How to test changes / Special notes to the reviewer**:
1. Run operator locally using operator-sdk or using operatorhub
2. Get the url to login to RH-SSO
`oc get route sso -n openshift-gitops`

Access the url with https in your browser and use the below commands to fetch the credentials.

```
oc exec sso-1-pc44p -n openshift-gitops -- "env" | grep SSO_ADMIN_USERNAME
```
--> Output: SSO_ADMIN_USERNAME=SbjLgMQp

```
 oc exec sso-1-pc44p -n openshift-gitops -- "env" | grep SSO_ADMIN_PASSWORD
```

### CODE REVIEW

**Comment by sbose78** [comment]
Does this configure Argocd to login with this instance of keycloak( and using Openshift idp) as well?

**Comment by iam-veeramalla** [comment]
> rgocd to login with this inst

This will only install RHSSO using template instance. Creating keycloak resources and openshift IDP will be a follow up story

**Comment by wtam2018** [comment]
/hold 
code freeze until v1.1.0 is shipped.

**Comment by iam-veeramalla** [comment]
@sbose78 Can we close this stale PR ? We merged the SSO feature already.

**Comment by iam-veeramalla** [comment]
Closing the PR. This PR was initially created with an intent to support RHSSO only for the default instance in openshift-gitops operator. 

We came up with a better design to support/create and configure RHSSO for every argocd instance. This feature is developed and merged in upstream to support SSO using keycloak for every Argo CD instance.
https://github.com/argoproj-labs/argocd-operator/commit/f11b440c49df0ea3ead9d33d3484c7160b1397ef
https://github.com/argoproj-labs/argocd-operator/commit/f2679790645d9a1d891b451ceda1ff5148123cf9

**Pull request closed without merging**
