### PR TITLE
feat: Bump k8s version to 1.21.0

### PR DESCRIPTION
**Pull request by iam-veeramalla**
**What type of PR is this?**
> /kind enhancement

**What does this PR do / why we need it**:
1. update the k8s client.
2.  add argo-cd as a dependency. This is needed for e2e testing. 
     Example: Create an argo-cd application and verify if gitops-operator reads the application and deploys the resources from source to cluster.

**Have you updated the necessary documentation?**
NA

**Which issue(s) this PR fixes**:
NA

**How to test changes / Special notes to the reviewer**:
1. Create a new e2e test which creates argo-cd application
2. Verify if argo-cd controller in gitops-operator reads the application resource and performs required action.

### CODE REVIEW

**Review by varshab1210 — CHANGES_REQUESTED** [review]
@iam-veeramalla  Ci is failing due to https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-developer_gito[…]-developer-gitops-operator-master-unit/1382621612968251392. Can you please commit the ```go.som```  file after running ```go mod```  tidy locally

**Comment by iam-veeramalla** [comment]
> @iam-veeramalla Ci is failing due to [https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-developer_gito[…]-developer-gitops-operator-master-unit/1382621612968251392](https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-developer_gito%5B%E2%80%A6%5D-developer-gitops-operator-master-unit/1382621612968251392). Can you please commit the `go.som` file after running `go mod tidy` locally

Thanks Varsha !!

**Comment by jannfis** [comment]
I don't understand why we need the dependency to Argo CD here - according to the go.mod, it's an indirect dependency and also to v1.8.7. Pulling that in adds a whole lot of complexity and also lots of other dependencies. 

What is the use-case behind it?

**Comment by iam-veeramalla** [comment]
> ds a whole lot of complexity and also lots of other dependencies.
> 
> What is the use-case behind it?

As part of e2e test, test team wants to create application CRs.

**Comment by wtam2018** [comment]
I would agree.   Let's not adding unnecessary dependencies.

**Review by wtam2018 — COMMENTED** [review]
I am not sure we should do this change right now.   I am looking at the operator-sdk v1.6.1.  I generates a go.mod that still uses `k8s.io/client-go v0.19.2`.   You've brought in some new dependencies from containerd and microsoft and there is a bunch of "replaces".  I am not sure that is a good idea.

**Comment by iam-veeramalla** [comment]
> I am not sure we should do this change right now. I am looking at the operator-sdk v1.6.1. I generates a go.mod that still uses `k8s.io/client-go v0.19.2`. You've brought in some new dependencies from containerd and microsoft and there is a bunch of "replaces". I am not sure that is a good idea.

Sure William, I will close this PR. Currently we are using 1.18 , I just thought of updating it to 1.21. We can take this sometime later.

**Pull request closed without merging**
