### PR TITLE
Upgrade Argo CD Operator to pick up TLS race cond fix

### PR DESCRIPTION
**Pull request by jgwest**
**What type of PR is this?**
/kind bug

**What does this PR do / why we need it**:
- Update argocd-operator dependency to latest from `master` branch, to pick up https://github.com/argoproj-labs/argocd-operator/pull/1469

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

N/A

**Test acceptance criteria**:

* [ ] Unit Test
* [ ] E2E Test

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Review by anandf — APPROVED** [review]
LGTM

**Comment by jgwest** [comment]
/retest

Mainly failed on cluster setup, but also failed on:
```
        --- FAIL: kuttl/harness/1-063_validate_statefulset_restart (1264.11s)
        --- FAIL: kuttl/harness/1-083_validate_resource_customization_subkeys (1203.94s)
        --- FAIL: kuttl/harness/1-042_validate_status_host (1203.90s)
        --- FAIL: kuttl/harness/1-062_validate_extra_config (1203.96s)
        --- FAIL: kuttl/harness/1-058_validate_prometheus_rule (1206.35s) 
```

**Comment by jgwest** [comment]
/retest
```
 time="2024-08-14T19:48:19Z" level=fatal msg="Failed to run bundle: error waiting for CSV to install: timed out waiting for the condition\n"
{"component":"entrypoint","error":"wrapped process failed: exit status 1","file":"sigs.k8s.io/prow/pkg/entrypoint/run.go:84","func":"sigs.k8s.io/prow/pkg/entrypoint.Options.internalRun","level":"error","msg":"Error executing test process","severity":"error","time":"2024-08-14T19:48:19Z"} 
```

**Comment by jgwest** [comment]
/retest
```
        --- FAIL: kuttl/harness/1-080_validate_regex_support_argocd_rbac (1204.20s)
        --- FAIL: kuttl/harness/1-079_validate_vars_for_notificaitons (1203.15s)
        --- FAIL: kuttl/harness/1-063_validate_statefulset_restart (1248.45s)
        --- FAIL: kuttl/harness/1-039_validate_fix_argocd-tls-certs-cm (1203.32s)
        --- FAIL: kuttl/harness/1-052_validate_rolebinding_number (6.25s)
        --- FAIL: kuttl/harness/1-067_validate_redis_secure_comm_no_autotls_ha (329.75s)
        --- FAIL: kuttl/harness/1-104_validate_applicationset_tls_scm_volume_mount (126.80s) 
```

**Pull request merged**
