### PR TITLE
Sync go version

### PR DESCRIPTION
**Pull request by amitkrout**
**What type of PR is this?**
/kind cleanup

**What does this PR do / why we need it**:
go version should match with https://github.com/redhat-developer/gitops-operator/blob/master/Dockerfile#L1

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes NA

**How to test changes / Special notes to the reviewer**:
go version reference should be same across the codebase

### CODE REVIEW

**Comment by sbose78** [comment]
+1 on the change. Badly needed.

**Review by wtam2018 — COMMENTED** [review]
/lgtm
/approve
Thanks @amitkrout !

**Pull request merged**
