### PR TITLE
Add acceptance test for CVP testing

### PR DESCRIPTION
**Pull request by bluengo**
**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

> /kind bug
> /kind cleanup
> /kind failing-test

/kind enhancement

> /kind documentation
> /kind code-refactoring

**What does this PR do / why do we need it**:
In order to run tests within the CVP pipeline (GITOPS-2466/GITOPS-2775), we need to add a small set of kuttl tests checking the basic functionality of the operator. This test checks:

1. Status of Deployments in the openshift-gitops namespace.
2. Status of the StatefulSet in the openshift-gitops namespace.
3. Status of the Services in the openshift-gitops namespace.
4. Status of the Routes in the openshift-gitops namespace.

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Test acceptance criteria**:

* [ ] Unit Test
* [X] E2E Test

**How to test changes / Special notes to the reviewer**:

You can try this test by running this command from the root directory of the [repo](https://github.com/bluengo/gitops-operator):

```bash
kubectl kuttl test ./test/openshift/e2e/acceptance --config ./test/openshift/e2e/sequential/kuttl-test.yaml --test 1-001_validate_openshift_gitops
```

### CODE REVIEW

**Comment by wtam2018** [comment]
@bluengo we do not need to make change to the kuttl tests in gitops operator in GitHub. CVP tests are only run in CPaaS downstream.

**Comment by varshab1210** [comment]
Closing this, please reopen if required

**Pull request closed without merging**
