### PR TITLE
doc: add index for usage guide

### LINKED ISSUE #282: Create index page for OpenShift GitOps user guide.
**Describe the bug**
A index page to look at the contents of the documents or directly jump to a specific topic in the document would be much helpful.

### PR DESCRIPTION
**Pull request by saumeya**
**What type of PR is this?**
/kind documentation

**What does this PR do / why we need it**:
Add index section for Usage guide 

**Have you updated the necessary documentation?**

* [x] Documentation update is required by this PR.
* [x] Documentation has been updated.

**Which issue(s) this PR fixes**:
 
Fixes #282 

**Test acceptance criteria**:

* [ ] Unit Test
* [ ] E2E Test

**How to test changes / Special notes to the reviewer**: Preview
preview

### CODE REVIEW

**Comment by saumeya** [comment]
As mentioned by Jaideep, the hamburger icon in the readme sections, works like an index for all the sections and sub sections. I have just added Table of Content for the main headings for better accessibility of the doc.

**Review by iam-veeramalla — APPROVED** [review]
Looks much better now, Thanks @saumeya

**Pull request merged**
