### PR TITLE
Fix dynamic plugin test for OCP 4.15

### PR DESCRIPTION
**Pull request by varshab1210**
**What type of PR is this?**

/kind failing-test

**What does this PR do / why we need it**:

Fixes 1-085_validate_dynamic_plugin_installation test for OCP 4.15 as dynamic plugin is enabled by default for OCP v4.15+

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

**Test acceptance criteria**:

* [ ] Unit Test
* [ ] E2E Test

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Review by ciiay — APPROVED** [review]
LGTM
The new code seems simply checks the OCP version and if it's greater than 4.15 then it skips environment variable setting.

**Comment by svghadi** [comment]
**Ignore this comment. I am trying out cherry-pick bot.**

/cherry-pick v1.10

**Pull request merged**
