### PR TITLE
Revert "bug: remove additional operator-backed items in the developer…

### PR DESCRIPTION
**Pull request by shubhamagarwal19**
… catalog in Dev Console (#165)"

This reverts commit 8bae146aa37cf6a6eca506ee0e28e2a9272760b1.

Need to use Annotations to hide internal APIs ... 
https://github.com/operator-framework/operator-lifecycle-manager/pull/1097#issuecomment-561177674

**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

> /kind bug
> /kind cleanup
> /kind failing-test
> /kind enhancement
> /kind documentation
> /kind code-refactoring

**What does this PR do / why we need it**:

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

**Test acceptance criteria**:

* [ ] Unit Test
* [ ] E2E Test

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by iam-veeramalla** [comment]
@shubhamagarwal19 what about marking gitopsservice as an internal object using the annotation `operators.operatorframework.io/internal-objects`

Are you planning to raise a separate PR for that change ?

**Comment by jannfis** [comment]
> Are you planning to raise a separate PR for that change ?

Yes, please make it a separate PR.

**Pull request merged**
