### PR TITLE
pick up reconcile redis/dex fixes from upstream argocd operator

### PR DESCRIPTION
**Pull request by shubhamagarwal19**
Picks up following fixes - 
https://github.com/argoproj-labs/argocd-operator/pull/241
https://github.com/argoproj-labs/argocd-operator/pull/242

### CODE REVIEW

**Review by bigkevmcd — APPROVED** [review]

**Comment by wtam2018** [comment]
@shubhamagarwal19 

Thanks for the PR
Please add testing info.    
* How to test your fix?
* What testing has been done?

**Comment by wtam2018** [comment]
/hold
assessing impact of argoproj-labs/argocd-operator#241

**Pull request merged**
