### PR TITLE
chore: Upgrade argocd-operator versions v0.13.0

### PR DESCRIPTION
**Pull request by Mangaal**
**What type of PR is this?**
 /kind chore

**What does this PR do / why we need it**:
Upgrade argocd-operator versions

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

**Test acceptance criteria**:

* [ ] Unit Test
* [ ] E2E Test

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by Mangaal** [comment]
ok-to-test

**Review by anandf — APPROVED** [review]
lgtm

**Pull request merged**
