### PR TITLE
Upgrade v1.13 to Argo Rollouts manager v0.0.3.1: e054d35fd0d9dad6b9ae26efa60f43cadc…

### PR DESCRIPTION
**Pull request by jgwest**
**What type of PR is this?**
/kind bug

**What does this PR do / why we need it**:
- Upgrade to latest version of Argo Rollouts v0.0.3.1 to address issues identified when switching from cluster/namespace-scoped Rollouts installs

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

**Test acceptance criteria**:

* [ ] Unit Test
* [ ] E2E Test

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Comment by jgwest** [comment]
/retest

```
        --- FAIL: kuttl/harness/1-067_validate_redis_secure_comm_no_autotls_ha (331.87s) 
```

**Comment by jgwest** [comment]
/retest

Same as above

**Comment by jparsai** [comment]
Thanks @jgwest 
/lgtm

**Review by anandf — APPROVED** [review]
LGTM

**Pull request merged**
