### PR TITLE
add documentation for new DCO requirements

### PR DESCRIPTION
**Pull request by reginapizza**
**What type of PR is this?**
> /kind documentation

**What does this PR do / why we need it**:
Now that DCO checks are enabled, this will add documentation about it as requested by Red Hat Legal team. 

**Which issue(s) this PR fixes**:
https://issues.redhat.com/browse/GITOPS-2122

### CODE REVIEW

**Comment by fbricon** [comment]
@reginapizza you enabled the DCO app for the entire redhat-developer org, but this is not necessary, as the DCO strategy we're following, as documented in this very PR, is implicit DCO, (CoreOS style). 

> By contributing to this project you agree to the Developer Certificate of
Origin (DCO)

Therefore it's no longer required to sign-off commits.

I will disable the DCO app

**Comment by reginapizza** [comment]
sorry about that Fred, I'll make sure it's only our repositories that have it enabled. Thank you!

**Comment by fbricon** [comment]
@reginapizza no you don't need the DCO app anymore after this PR is merged, since you're making contributions implicitly according to this project's DCO

**Comment by fbricon** [comment]
... unless other repos have not yet moved to implicit DCO, then yes they can still use the DCO app

**Comment by reginapizza** [comment]
@fbricon ah understood, thank you!

**Pull request merged**
