### PR TITLE
chore: update operator-sdk to v1.11.0

### PR DESCRIPTION
**Pull request by iam-veeramalla**
Signed-off-by: iam-veeramalla <abhishek.veeramalla@gmail.com>

**What type of PR is this?**
> /kind enhancement

**What does this PR do / why we need it**:
There's been a change in the operator-sdk version 1.10.1 to not generate a file (bundle/manifests/gitops-operator_v1_serviceaccount.yaml) when running make bundle, and in version 1.11.0 the presence of that file will actually cause make bundle to error out. This PR is to remove that file and regenerate the bundle artifacts using operator-sdk version 1.11.0

**How to test changes / Special notes to the reviewer**:
Install v1.11.0 version of operator-sdk
run `make bundle`. You should not run into any issues.

### CODE REVIEW

**Comment by iam-veeramalla** [comment]
@chetan-rns tests passed, can you please review

**Review by chetan-rns — APPROVED** [review]
Thanks @iam-veeramalla 

/lgtm
/approve

**Pull request merged**
