### PR TITLE
refactoring: move openshift package from argocd-operator to gitops-operator 

### PR DESCRIPTION
**Pull request by jaideepr97**
**What type of PR is this?**
> Uncomment only one ` /kind` line, and delete the rest.
> For example, `> /kind bug` would simply become: `/kind bug`

> /kind bug
> /kind cleanup
> /kind failing-test
> /kind enhancement
> /kind documentation
/kind code-refactoring

**What does this PR do / why we need it**:
Moves the openshift package (containing logic for opensihft-gitops specific hooks) from argocd-operator to itops-operator as a part of refactoring effort 
see https://github.com/argoproj-labs/argocd-operator/pull/567#issuecomment-1080571667

**Have you updated the necessary documentation?**

* [ ] Documentation update is required by this PR.
* [ ] Documentation has been updated.

**Which issue(s) this PR fixes**:

Fixes #?

**Test acceptance criteria**:

* [ ] Unit Test
* [ ] E2E Test

**How to test changes / Special notes to the reviewer**:

### CODE REVIEW

**Review by saumeya — COMMENTED** [review]
Tested the changes and works for me!

**Comment by jaideepr97** [comment]
@iam-veeramalla PTAL when possible please, TIA!

**Pull request merged**
